version: 2
jobs:
  build:
    working_directory: ~/robocup-training
    docker:
      - image: silex/emacs:26-dev
    steps:
        # Install cask
      - checkout
      - run: git config --global user.name "$GIT_USERNAME" && git config --global user.email "$GIT_EMAIL"
      - run: git clone "$CIRCLE_REPOSITORY_URL" html && cd html && git checkout gh-pages && cd ..
      - run: ~/.cask/bin/cask install
        # Generate build files to /html
      - run: ~/.cask/bin/cask eval "(progn (require 'robocup-training) (my-org-publish))"
      - deploy:
          name: Deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd html && git add . && git commit -m "Autoupdate html sources" || true && git push https://$GH_TOKEN@github.com/RoboJackets/robocup-training gh-pages || true
            fi
